<div class="layout">
      <header id="top">
        <a href="/">Strona główna</a>
      </header>

      <nav>
        <ul>
          <li>
              <a href="/cats/galeria"><b>Galeria kotów</b></a>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
          <li>
            <?php if (isset($_SESSION['user_id'])): ?>
                <form method="post" style="display:inline;">
                    <button type="submit" name="logout" style="background:none; border:none; color:blue; text-decoration:underline; cursor:pointer;">
                        Wyloguj się
                    </button>
                </form>
            <?php endif; ?>
          </li>
        </ul>
      </nav>
      
      <footer>
        <div id="footer">
              <p>Maria Rek | Wytwarzanie aplikacji internetowych | 2024/2025</p> 
        </div>
      </footer>