<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria szczurów</title>
    <link rel="stylesheet" type="text/css" href="../static/style/singlecat.css" />
  </head>

  <body>
    <div class="layout">
      <header id="top">
        <!-- LOGO WYGENEROWANE PRZEZ AI -->
        <img src="./static/resource/logo.png" width="150" height="150">
        <br/>
        <a href="/">Strona główna</a>
      </header>

      <nav>
        <ul>
          <li>
            <div class="dropdown">
              <button class="dropbtn"><b>Galeria</b></button>
              <div class="dropdown-content">
                <a href="/rats/yato">Yato</a>
                <a href="/rats/ashe">Ashe</a>
                <a href="/rats/akira">Akira</a>
                <a href="/rats/galeria">Galeria szczurków</a>
              </div>
            </div>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
        </ul>
      </nav>

      <div class="content">
        Melon i Fin to dwa koty, lecz główną rolę odgrywa tutaj Melon. Na wspólnym koncie tiktok
        właściciel kotów poza normalnymi filmami z wizerunkiem kotów, prowadzi również serię 
        "Melon be Smellin'" (transl. Melon wącha), w której Melon wącha różne przedmioty.
        Mimo że przedmioty nie są nadzwyczajnie nietypowe czy niespotykane, Melon miewa 
        przesadne reakcje na niektóre z nich, co jest głównym powodem popularności serii.
        Fin nie jest tak popularny jak Melon, lecz również ma swoją serię filmów o tematyce wąchania - 
        "Fin be Sniffin'". Statystyki dwóch serii można zobaczyć <strong><a href="https://docs.google.com/spreadsheets/d/1IVoW9sCDZsoJlvA2IcdPXOvUmlb2K58bBSVNTQGkZYU/edit#gid=0" target="_blank">tutaj</a></strong>.
      </div>

      <footer>
        <div id="footer">
              <p>Maria Rek | Wytwarzanie aplikacji internetowych | 2024/2025</p> 
        </div>
      </footer>

      <main>
        <p>Akira</p>
      </main>
    </div>
  </body>
</html>
