<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria szczurów</title>
    <link rel="stylesheet" type="text/css" href="../static/style/singlecat.css" />
  </head>

  <body>
    
    <div class="layout">
      <header id="top">
        <!-- LOGO WYGENEROWANE PRZEZ AI -->
        <img src="./static/resource/logo.png" width="150" height="150">
        <br/>
        <a href="/">Strona główna</a>
      </header>

      <nav>
        <ul>
          <li>
            <div class="dropdown">
              <button class="dropbtn"><b>Galeria</b></button>
              <div class="dropdown-content">
                <a href="/rats/yato">Yato</a>
                <a href="/rats/ashe">Ashe</a>
                <a href="/rats/akira">Akira</a>
                <a href="/rats/galeria">Galeria szczurków</a>
              </div>
            </div>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
        </ul>
      </nav>

      <div class="content">
        Panko jest kotem o ubarwieniu "calico", czyli trójkolorowym. Ma ona
        lekkiego zeza, co mimo negatywnych efektów na jej zdrowie dodaje do jej
        uroku. Bardzo lubi ludzkie jedzenie, przez co gdy jest ono
        przygotowywane często kładzie głowę na stół i patrzy na proces
        przyrządzania. Właścicielka Panko co jakiś czas ubiera kota w nietypowe
        stroje i kostiumy, po czym udostępnia efekt na swoich social mediach
        poświęconych swojemu czworonogowi.
      </div>

      <footer>
        <div id="footer">
              <p>Maria Rek | Wytwarzanie aplikacji internetowych | 2024/2025</p> 
        </div>
      </footer>

      <main>
        <h2>Ashe</h2>
      </main>

    </div>
  </body>
</html>
