<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Szczurów</title>
    <link rel="stylesheet" type="text/css" href="/static/style/singlecat.css" />
  </head>

  <body>
    <div class="layout">
      <header id="top">
        <!-- LOGO WYGENEROWANE PRZEZ AI -->
        <img src="./static/resource/logo.png" width="150" height="150">
        <br/>
        <a href="/">Strona główna</a>
      </header>

      <nav>
        <ul>
          <li>
            <div class="dropdown">
              <button class="dropbtn"><b>Galeria</b></button>
              <div class="dropdown-content">
                <a href="/rats/yato">Yato</a>
                <a href="/rats/ashe">Ashe</a>
                <a href="/rats/akira">Akira</a>
                <a href="/rats/galeria">Galeria szczurków</a>
              </div>
            </div>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
        </ul>
      </nav>

      <div class="content">
        Kot Uni posiada dedykowane
        <strong
          ><a href="https://www.tiktok.com/@unicouniuni?lang=en"
            >konto na tiktoku</a
          ></strong
        >, gdzie jego właściciel publikuje filmy z jego wizerunkiem. Jest kotem
        w "smokingu", o czarno-białym namaszczeniu z charakterystycznym znakiem
        przy jamie ustnej układającym się w "3". Z powodu tej cechy urzekł on
        ogromne ilości internautów, jak i mnie. Właściciel często przywdziewa
        młodą gwiazdę w intrygujące, wielokolorowe stroje.
        Stworzenie konta na tiktoku i osiągnięcie popularności rzędu milionów
        wyświetleń pod każdym filmem to nie lada wyczyn. Właściciel Uni wykorzystał
        to, by stworzyć pluszaka na wzór kota, podpisując umowę z firmą produkującą
        związane z popkulturą gadżety. 
      </div>

      <footer>
        <div id="footer">
              <p>Maria Rek | Wytwarzanie aplikacji internetowych | 2024/2025</p> 
        </div>
      </footer>

      <main>
        <h2>Yato</h2>
      </main>

    </div>
  </body>
</html>
