<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Szczurów</title>
    <link rel="stylesheet" type="text/css" href="../static/style/galeria.css" />
  </head>

  <body>
    <div class="layout">
      <header id="top">
        <!-- LOGO WYGENEROWANE PRZEZ AI -->
        <img src="./static/resource/logo.png" width="150" height="150">
        <br/>
        <a href="/">Strona główna</a>
      </header>

      <nav>
        <ul>
          <li>
            <div class="dropdown">
              <button class="dropbtn"><b>Koty</b></button>
              <div class="dropdown-content">
              <a href="/rats">Wstęp</a>
                <a href="/rats/yato">Yato</a>
                <a href="/rats/ashe">Ashe</a>
                <a href="/rats/akira">Akira</a>
                <a href="/rats/galeria">Galeria szczurów</a>
              </div>
            </div>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
        </ul>
      </nav>

      <footer>
        <div id="footer">
              <p>Maria Rek | Wytwarzanie aplikacji internetowych | 2024/2025</p> 
        </div>
      </footer>

      <main>
        <h5>Galeria zdjęć szczurów</h5>
      </main>
      
      <div class="content">
        <?php
          $items_per_page = 2;
          $pictures = $rats;
          $totalItems = count($pictures);
          $currentPage = isset($_GET['page']) ? $_GET['page'] : 1;
          $urlPattern = '/rats/galeria?page=(:num)';
          $offset = ($currentPage - 1) * $items_per_page;
          $visiblePictures = array_slice($pictures, $offset, $items_per_page);
          $totalPages = ceil($totalItems / $items_per_page);

          $imageGap = 10;


          echo '<div class="gallery">';
            foreach ($visiblePictures as $picture) {
              $extension = pathinfo($picture['path'], PATHINFO_EXTENSION);
              echo '<a href="?action=viewimage&id=' . $picture['id'] . '">';
              echo '<img src="../images/miniaturki/' . $picture['id'] . '.' . $extension . '" alt="' . $picture['tytul'] . '"/>';
              echo '</a>';
              echo '<span> Tytuł: ' . $picture['tytul'];
              echo '<br />';
              echo 'Autor: ' . $picture['autor'] . '</span>';
              }
          echo '</div>';

          echo '<div class="paging">';
          for ($i = 1; $i <= $totalPages; $i++) {
              $isActive = ($i == $currentPage) ? 'active' : '';
              echo '<a href="?page=' . $i . '" class="' . $isActive . '">' . $i . '  </a>';
          }
          echo '</div>';
        ?>
      </div>
    </div>
  </body>
</html>
