<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Kotków</title>
    <link rel="stylesheet" type="text/css" href="./static/style/style.css" />
    <?php
    include "./static/partial/top.phtml";
    ?>
  </head>
  <body>
      <main>
        <h5>Galeria najsłodszych szczurków</h5>
      </main>
      
      <div class="content">
        <p>
        Witaj w galerii moich trzech najsłodszych szczurków! 🐾
        <br/>
        To trójka przesłodkich kawalerów, których możesz lepiej poznać, wybierając odpowiadającą im kategorię.
        <br/>
        Jeśli jednak chcesz od razu zobaczyć całą ekipę, po prostu przejdź do galerii i podziwiaj te słodziaki.
        <br/>
        Miłego oglądania! 🤍
        </p>
      </div>
  </body>
</html>