<?php
if (session_status() === PHP_SESSION_NONE) {
  session_start();
}
?>
<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Kotków</title>
    <link rel="stylesheet" type="text/css" href="./static/style/style.css" />
    <?php
    include "./static/partial/top.phtml";
    ?>
  </head>
  <body>
      <main>
        <h5>Galeria przesłodkich kotków</h5>
      </main>
      
      <div class="content">
        <p>
        Witaj w galerii przesłodkich kotków! 🐾
        <br/>
        Prześlij zdjęcie słodkiego kotka lub oglądaj w galerii zdjęcia innych użytkowników.
        <br/>
        Miłego oglądania! 🤍
        </p>
        <br/>
        <?php if (!empty($_SESSION['user'])): ?>
          <p>Witaj, <?= htmlspecialchars($_SESSION['user']); ?>!</p>
          <a href="/index.php?action=logout">Wyloguj się</a>
        <?php else: ?>
          <a href="/index.php?action=login">Zaloguj się</a>
          <a href="/index.php?action=register">Zarejestruj się</a>
      <?php endif; ?>
      </div>
  </body>
</html>