<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Kotków</title>
    <link rel="stylesheet" type="text/css" href="./static/style/style.css" />
    <?php
    include "./static/partial/top.phtml";
    ?>
  </head>
  <body>
      <main>
        <h5>Galeria przesłodkich kotków</h5>
      </main>
      
      <div class="content">
        <p>
        Witaj w galerii przesłodkich szczurków! 🐾
        <br/>
        Prześlij zdjęcie słodkiego kotka lub oglądaj w galerii zdjęcia innych użytkowników.
        <br/>
        Miłego oglądania! 🤍
        </p>
      </div>
  </body>
</html>