<?php
if (session_status() === PHP_SESSION_NONE) {
  session_start();
}
if (isset($_SESSION['user_id'])) {
    header("Location: galeria.phtml");
    exit();
}
?>
<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Kotków</title>
    <link rel="stylesheet" type="text/css" href="../static/style/style.css" />
  </head>

  <body>
    <div class="layout">
      <header id="top">
        <a href="/">Strona główna</a>
      </header>

      <nav>
        <ul>
          <li>
              <a href="/cats/galeria"><b>Galeria kotów</b></a>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
        </ul>
      </nav>
      
      <footer>
        <div id="footer">
              <p>Maria Rek | Wytwarzanie aplikacji internetowych | 2024/2025</p> 
        </div>
      </footer>

      <main>
        <h5>Zaloguj się</h5>
      </main>

      <div class="content">
        <form method="POST" action="/login">
          <label for="identifier">Nazwa użytkownika:</label>
          <input type="text" id="identifier" name="identifier" required>
          <br/>
          <label for="password">Hasło:</label>
          <input type="password" id="password" name="password" required>
          <br/>
          <button type="submit">Zaloguj się</button>
        </form>
        <br/>
        <p>Nie masz konta? <br/><a href="/index.php?action=register">Zarejestruj się tutaj</a></p>
      </div>
    </div>
  </body>
</html>
