<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Szczurów</title>
    <link rel="stylesheet" type="text/css" href="./static/style/style.css" />
    <?php
    include './static/partial/top.phtml';
    ?>
  </head>

  <body>
      <main>
        <div class="main">
          <p>Szczury</p>
        </div>
      </main>

      <div class="content">
          Z początku debiutu platformy TikTok, nie byłem przekonany co do jej
          polityki prywatności i przetwarzania danych osobowych. Jednakże, po
          dłuższym czasie zdecydowałem się na założenie konta, by móc przeglądać
          treści, które mnie interesują. Mimo tego, że większość życia byłem
          osobą preferującą psy, a na dodatek posiadającą alergię na koty, stały
          się one jednym z moich główych zainteresowań. Poniżej znajduje się
          lista zawierająca trzy konta poświęcone moim faworytom.
        <div class="catlistcontainer">
          <ul id="catlist">
            <li>
              <a href="./cats/uni.html">Yato</a>
            </li>
            <li>
              <a href="./cats/panko.html">Ashe</a>
            </li>
            <li>
              <a href="./cats/melonandfin.html">Akira</a>
            </li>
          </ul>
          <br />
          Każdy z tych kotów jest na swój sposób wyjątkowy, oraz posiada charakter będący wręcz kompletnym przeciwieństwem pozostałych kotów z listy. Jednakże, każdy z nich jest równie uroczy i zasługuje na uwagę.
        </div>
      </div>
    </div>
  </body>
</html>