<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Moja Galeria Szczurów</title>
    <link rel="stylesheet" type="text/css" href="../static/style/style.css" />
  </head>

  <body>
    <div class="popup">
      Jeśli to widzisz, twój JavaScript jest wyłączony. Proszę włącz go by mieć
      pewność, że strona działała poprawnie.
      <input
        type="button"
        class="accept"
        value="OK"
        onclick="this.parentNode.style.display = 'none';"
      />
    </div>
    <div class="layout">
      <header id="top"><a href="/">Strona główna</a></header>

      <nav>
        <ul>
          <li>
            <div class="dropdown">
              <button class="dropbtn"><b>Koty</b></button>
              <div class="dropdown-content">
                <a href="/cats">Wstęp</a>
                <a href="/cats/uni">Yato</a>
                <a href="/cats/panko">Ashe</a>
                <a href="/cats/melonandfin">Akira</a>
                <a href="/cats/galeria">Galeria szczurów</a>
              </div>
            </div>
          </li>
		      <li>
			      <a href="/upload"><b>Upload</b></a>
		      </li>
        </ul>
      </nav>
      
        <form id="bugForm" method="get" action="odbierz.php">
          Jeśli napotkałeś/aś jakieś problemy na stronie, proszę zgłoś je tutaj:
          <br />
          <br />
          <textarea id="txtbug" maxlength="200"></textarea>
          <input type="submit" value="Wyślij" />
        </form>

        <div id="confirmationMessage"></div>
        <a href="#top">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 12h-2v2H9v-2H7l5-5 5 5z"
            />
          </svg>
        </a>
      </footer>
      <main>
        <h5>Wysyłanie zdjęć</h5>
      </main>
        <div class="content">
        <!-- formularz!!! -->


        
        </div>
    </div>
    <script src="../static/resource/JavaScript/submittext.js"></script>

    <script src="../static/resource/JavaScript/mimo84-bootstrap-maxlength-335860e/src/bootstrap-maxlength.js"></script>
    <script>
      $("textarea").maxlength({
        alwaysShow: true,
        threshold: 10,
        warningClass: "label label-info",
        limitReachedClass: "label label-warning",
        placement: "top",
        preText: "used ",
        separator: " of ",
        postText: " chars.",
      });

      $(function () {
        $(document).tooltip();
      });

      $(function () {
        $("#draggable").draggable();
      });
    </script>
  </body>
</html>
