<!DOCTYPE html>
<html lang="pl-PL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Galeria Szczurów</title>
    <link rel="stylesheet" type="text/css" href="../static/style/style.css" />
  </head>

  <body>
    <div class="layout">
      <header id="top">
        <!-- LOGO WYGENEROWANE PRZEZ AI -->
        <img src="./static/resource/logo.png" width="150" height="150">
        <br/>
        <a href="/">Strona główna</a>
      </header>

      <nav>
        <ul>
          <li>
          <div class="dropdown">
            <button class="dropbtn"><b>Galeria</b></button>
            <div class="dropdown-content">
              <a href="/rats/yato">Yato</a>
              <a href="/rats/ashe">Ashe</a>
              <a href="/rats/akira">Akira</a>
              <a href="/rats/galeria">Galeria szczurków</a>
            </div>
          </div>
          </li>
          <li>
            <a href="/upload"><b>Upload</b></a>
          </li>
        </ul>
      </nav>

      <footer>
        <div id="footer">
          <p>Maria Rek | Wytwarzanie aplikacji internetowych | 2024/2025</p> 
        </div>
      </footer>
    
      <main>
        <h5>Przesyłanie zdjęć</h5>
      </main>

      <div class="content">
        <?php
          $picture = get_picture_by_id($id);
          $tytul = $picture['tytul'];
          $autor = $picture['autor'];
          $rat = $picture['rat'];
          $extension = pathinfo($picture['path'], PATHINFO_EXTENSION);
          $path = '../images/watermark/' . $id . '.' . $extension;
          echo '<img src="' . $path . '" alt="' . $tytul . '">';
          echo '<p> Tytuł: ' . $tytul . '</p>';
          echo '<p> Autor: ' . $autor . '</p>';
          echo '<p> Szczur: ' . $rat . '</p>';
        ?>
      </div>
    </div>
  </body>
</html>
